services:
  app:
    build: ./app
    container_name: mygreens-api-dev
    command: gunicorn -b :5000 --access-logfile - --error-logfile - app:app --reload
    user: mygreensapi
    ports:
      - 5000:5000
    volumes:
      - ./app:/home/mygreensapi